### ISSUE TITLE
Make it possible to have custom labels on scrape target

### ISSUE THREAD

**Issue by mfurquim** [flaviostutz/promster#5]
Some context requires the distinction by labels. This could be acquired by making the `key` as label e.g. if `REGISTRY_ETCD_BASE=/cct1/blue` and `REGISTRY_SERVICE=cfe`, we would have three different labels `cct1`, `blue`, and `cfe`.

**Comment by mfurquim** [comment]
How about this issue here, @flaviostutz?

**Comment by flaviostutz** [comment]
I didn't get your question... what do you mean by "some context requires the distinction by labels"?
Please explain with more details.

**Comment by mfurquim** [comment]
Currently we do green-blue testing on new version for the mobile. Green will contain the newest version and Blue the stable one. We gradually increases the number of users on Green from 1% to 100%. There are Grafana dashboards which compares the throughput, latency, and mainly error rate from green vs blue regions. When Promster is scraping I need to be able to add a label to identify from which region that data is from (green or blue?)

One way I see of doing that is to write the `REGISTRY_ETCD_BASE` with the labels I would like it to have, and have the Promster look at that `SCRAPE_ETCD_PATH`.

For instance, if it is written `/cct1/blue/cfe`, we would have those three as labels: `cct1`, `blue`, and `cfe`. We could drop it with recording rules if we don't need any.

**Comment by mfurquim** [comment]
Or maybe it would be easier to add an ENV `SCAPE_LABELS`, this way we can identify a cluster of Prometheus which is scraping from each region by attributing `SCRAPE_LABELS=green`, and it would add that to `prometheus.yml` config file.

**Comment by mfurquim** [comment]
I thought of something that might work. Together with `RECORD_RULE_1_NAME` and `RECORD_RULE_1_EXPR`, there could be a `RECORD_RULE_1_LABELS`, which contains the labels desired for that rule.

So these ENVs `RECORD_RULE_1_NAME=level1:http_requests_app_total:irate`, `RECORD_RULE_1_EXPR=sum(irate(http_requests_app_total[2m])) without (job,server_name,instance)`, and `RECORD_RULE_1_LABELS=site:cct1,region:blue` would generate this `rule.yml`:

```groups:
  - name: env-rules
    rules:
    - record: level1:http_requests_app_total:irate
      expr: sum(irate(http_requests_app_total[2m])) without (job,server_name,instance)
    labels:
      site: cct1
      region: blue```

**Comment by abilioesteves** [comment]
@flaviostutz, I’ll prepare a pull request for this issue. I also need something like it. For example, the [bb-promster](https://github.com/labbsr0x/bb-promster) project ends up overriding the startup.sh behavior just to deal with adding a special prsn label for each target.
