### ISSUE TITLE
Make it possible to scrape same targets, but different endpoint, and aggregate on a superior level

### ISSUE THREAD

**Issue by mfurquim** [flaviostutz/promster#6]
There has been needs to have multiple Promsters Level 1 scraping all targets and aggregate that with a single Promster Level 2. As per current implementation, that is not possible.

There is two registries that serves three purposes. The `SCRAPE_ETCD_PATH` which contains the targets to be scraped, and the `REGISTRY_ETCD_BASE/REGISTRY_SERVICE` which contains the Promsters of the same level to share the load AND the targets to the Promster Level 2 to aggregate.

Example 1: Bearing in mind `t*` being the scrape target of `p1-*`, which are Promster Level 1; and `p2-*` are Promster Level 2, which will aggregate the information of `p1-*`. Suppose we have the following registries:
```
/webservers/t1
/webservers/t2
/webservers/t3
/prom1/p1-1
/prom1/p1-2
/prom2/p2-1
```

We would have the following scenario:
```
  ╭──╮ ╭──╮ ╭──╮
  │t1│ │t2│ │t3│
  ╰──╯ ╰──╯ ╰──╯
   │    ╱     │
 ┌──────┐ ┌──────┐
 │ P1-1 │ │ P1-2 │
 └──────┘ └──────┘
        ╲ ╱
      ┌──────┐
      │ P2-1 │
      └──────┘
```

If we wanted to have both Promster Level 1 scraping the same target AND having both being aggregated to Promster Level 2, we would have to add a registry to indicate the Promster at that level would like to share the load. This way, if we had the following registries
```
/webservers/t1
/webservers/t2
/webservers/t3
/shareloadprom1/p1-1
/shareloadprom1/p1-2
/prom1/p1-1
/prom1/p1-2
/prom2/p2-1
```

We could have a scenario like this possible:
```
  ╭──╮ ╭──╮ ╭──╮
  │t1│ │t2│ │t3│
  ╰──╯ ╰──╯ ╰──╯
   │╲   ╱╲   ╱│
 ┌──────┐ ┌──────┐
 │ P1-1 │ │ P1-2 │
 └──────┘ └──────┘
        ╲ ╱
      ┌──────┐
      │ P2-1 │
      └──────┘
```
At the end, there would have three distinct registries for each Promster: A) a registry which contains the address of the target; B) a registry which contains it's brothers to share the load; C) a registry which tells a superior level to scrape themselves. It is possible to make it backward compatible by setting the sharing-load registry to the base+service registry, in other words, `Registry B <- Registry C`

**Comment by flaviostutz** [comment]
Let’s see if I understood your requirements. You need to avoid sharding during scrape on a given level, so that all instances of the same level will scrape the same set of targets, right?

**Comment by mfurquim** [comment]
@flaviostutz yes, that is it :)

**Comment by flaviostutz** [comment]
This scenario is the same as if you wanted to replicate data among Promster instances that would handle queries among a set of - same data - Promsters instances so that if the load increases you would only create more instances. 
This is possible with the current implementation. Just create N services in docker-compose (one for each instance). On each, use a different REGISTRY_SERVICE name so that no sharding distribution will take place.

**Comment by flaviostutz** [comment]
For this to work with Swarm instance scale, I will create an environment called SCRAPE_SHARDING_DISABLE=true so that all instances will scrape the same set of servers (as sharding with consistent hash will be disabled).

**Comment by flaviostutz** [comment]
For those who needs registration to take place but no sharding to take place, I will create ENV SCRAPE_SHARD_ENABLE=false

**Comment by flaviostutz** [comment]
Please, test the latest version (1.1.0) for this feature (see example in readme) and close this issue if everything is right (I've done dev tests on myself).

**Comment by mfurquim** [comment]
@flaviostutz I just tested and it works!
Thanks!

**Comment by mfurquim** [comment]
Well, it did work for one case, but it messed with another.
Here is the deal. I have a promster level 1 scraping 200 targets with the endpoint `/metrics-http`. I need another promster level 1 to scrape the same 200 targets but at the endpoint `/metrics-iib`. The `SCRAPE_SHARD_ENABLE=false` does work for not sharing the scrape load between `promster-level1-http` and `promster-level1-iib`, but it does mess up the distribution between same service containers when their number is increased. Meaning if I have two containers of promster-level1-http, they both will scrape all 200 targets, when in fact I want 100 targets for each.

**Comment by mfurquim** [comment]
Well, it did work for one case, but it messed with another.
Here is the deal. I have a promster level 1 scraping 200 targets with the endpoint `/metrics-http`. I need another promster level 1 to scrape the same 200 targets but at the endpoint `/metrics-iib`. The `SCRAPE_SHARD_ENABLE=false` does work for not sharing the scrape load between `promster-level1-http` and `promster-level1-iib`, but it does mess up the distribution between same service containers when their number is increased. Meaning if I have two containers of promster-level1-http, they both will scrape all 200 targets, when in fact I want 100 targets for each.

**Comment by abilioesteves** [comment]
@flaviostutz, from what I understand, Matheus should have been working with two different observation clusters, not one. If you have different metric endpoints, there is no reason to federate them together. I think this issue should be closed. Thanks!

**Comment by mfurquim** [comment]
The goal was to facilitate maintainability when adding new contexts to be scraped by Promster, in a way that one would only have to add a level one Promster and a superior level would aggregate and automatically showing data on Grafana. But if there has been a better solution, this issue can indeed be closed.

**Comment by abilioesteves** [comment]
@mfurquim, this is complicated since the information differs at the application domain. For a better experience with promster, you should deploy one observation cluster per app. Otherwise promster can get quite cumbersome and difficult to maintain and evolve. Thanks @mfurquim!

**Comment by flaviostutz** [comment]
Great, guys! closing this for now
